-- Seed data for ChatBot tu van y te
-- Idempotent: uses INSERT .. ON CONFLICT .. DO UPDATE

-- basic_data
INSERT INTO basic_data (id, first_name, last_name, birth_date, address, city, state, mobile_number, email_address, password, speciality, is_doctor, logged_in) VALUES (1, 'Khiem', 'Pham', '2000-01-01', '123 Nguyen Trai', 'Ho Chi Minh', 'Ho Chi Minh', 912345678, 'khiem@gmail.com', '123456', NULL, FALSE, FALSE) ON CONFLICT (id) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, birth_date=EXCLUDED.birth_date, address=EXCLUDED.address, city=EXCLUDED.city, state=EXCLUDED.state, mobile_number=EXCLUDED.mobile_number, email_address=EXCLUDED.email_address, password=EXCLUDED.password, speciality=EXCLUDED.speciality, is_doctor=EXCLUDED.is_doctor, logged_in=EXCLUDED.logged_in;
INSERT INTO basic_data (id, first_name, last_name, birth_date, address, city, state, mobile_number, email_address, password, speciality, is_doctor, logged_in) VALUES (2, 'Lan', 'Pham', '2005-06-15', '123 Nguyen Trai', 'Ho Chi Minh', 'Ho Chi Minh', 934567890, 'lan.member@gmail.com', '123456', NULL, FALSE, FALSE) ON CONFLICT (id) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, birth_date=EXCLUDED.birth_date, address=EXCLUDED.address, city=EXCLUDED.city, state=EXCLUDED.state, mobile_number=EXCLUDED.mobile_number, email_address=EXCLUDED.email_address, password=EXCLUDED.password, speciality=EXCLUDED.speciality, is_doctor=EXCLUDED.is_doctor, logged_in=EXCLUDED.logged_in;
INSERT INTO basic_data (id, first_name, last_name, birth_date, address, city, state, mobile_number, email_address, password, speciality, is_doctor, logged_in) VALUES (10, 'An', 'Nguyen', '1985-03-01', '45 Le Loi', 'Ho Chi Minh', 'Ho Chi Minh', 988111222, 'dr.an@gmail.com', '123456', 'Family Physician', TRUE, FALSE) ON CONFLICT (id) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, birth_date=EXCLUDED.birth_date, address=EXCLUDED.address, city=EXCLUDED.city, state=EXCLUDED.state, mobile_number=EXCLUDED.mobile_number, email_address=EXCLUDED.email_address, password=EXCLUDED.password, speciality=EXCLUDED.speciality, is_doctor=EXCLUDED.is_doctor, logged_in=EXCLUDED.logged_in;
INSERT INTO basic_data (id, first_name, last_name, birth_date, address, city, state, mobile_number, email_address, password, speciality, is_doctor, logged_in) VALUES (11, 'Bao', 'Tran', '1988-07-10', '88 Tran Hung Dao', 'Ho Chi Minh', 'Ho Chi Minh', 977333444, 'dr.bao@gmail.com', '123456', 'Cardiologist', TRUE, FALSE) ON CONFLICT (id) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, birth_date=EXCLUDED.birth_date, address=EXCLUDED.address, city=EXCLUDED.city, state=EXCLUDED.state, mobile_number=EXCLUDED.mobile_number, email_address=EXCLUDED.email_address, password=EXCLUDED.password, speciality=EXCLUDED.speciality, is_doctor=EXCLUDED.is_doctor, logged_in=EXCLUDED.logged_in;

-- health_data
INSERT INTO health_data (id, gender, age, blood_group, weight, height, obesity, disability, fitzpatrick, allergies, diabetes, thyroid, cancer, covid, asthma, hiv_aids, addiction) VALUES (1, 'Male', 26, 'O+', 68, 172, 'No', 'No', 'Type 3', 'None', 'No', 'No', 'No', 'No', 'No', 'No', 'No') ON CONFLICT (id) DO UPDATE SET gender=EXCLUDED.gender, age=EXCLUDED.age, blood_group=EXCLUDED.blood_group, weight=EXCLUDED.weight, height=EXCLUDED.height, obesity=EXCLUDED.obesity, disability=EXCLUDED.disability, fitzpatrick=EXCLUDED.fitzpatrick, allergies=EXCLUDED.allergies, diabetes=EXCLUDED.diabetes, thyroid=EXCLUDED.thyroid, cancer=EXCLUDED.cancer, covid=EXCLUDED.covid, asthma=EXCLUDED.asthma, hiv_aids=EXCLUDED.hiv_aids, addiction=EXCLUDED.addiction;
INSERT INTO health_data (id, gender, age, blood_group, weight, height, obesity, disability, fitzpatrick, allergies, diabetes, thyroid, cancer, covid, asthma, hiv_aids, addiction) VALUES (2, 'Female', 21, 'A+', 52, 160, 'No', 'No', 'Type 3', 'Pollen', 'No', 'No', 'No', 'No', 'No', 'No', 'No') ON CONFLICT (id) DO UPDATE SET gender=EXCLUDED.gender, age=EXCLUDED.age, blood_group=EXCLUDED.blood_group, weight=EXCLUDED.weight, height=EXCLUDED.height, obesity=EXCLUDED.obesity, disability=EXCLUDED.disability, fitzpatrick=EXCLUDED.fitzpatrick, allergies=EXCLUDED.allergies, diabetes=EXCLUDED.diabetes, thyroid=EXCLUDED.thyroid, cancer=EXCLUDED.cancer, covid=EXCLUDED.covid, asthma=EXCLUDED.asthma, hiv_aids=EXCLUDED.hiv_aids, addiction=EXCLUDED.addiction;

-- user_stats
INSERT INTO user_stats (id, account_created_on, number_of_appointments, number_of_virtual_appointments, number_of_documents_uploaded, number_of_members_added) VALUES (1, '2026-04-19', 1, 1, 1, 1) ON CONFLICT (id) DO UPDATE SET account_created_on=EXCLUDED.account_created_on, number_of_appointments=EXCLUDED.number_of_appointments, number_of_virtual_appointments=EXCLUDED.number_of_virtual_appointments, number_of_documents_uploaded=EXCLUDED.number_of_documents_uploaded, number_of_members_added=EXCLUDED.number_of_members_added;
INSERT INTO user_stats (id, account_created_on, number_of_appointments, number_of_virtual_appointments, number_of_documents_uploaded, number_of_members_added) VALUES (2, '2026-04-19', 0, 0, 0, 0) ON CONFLICT (id) DO UPDATE SET account_created_on=EXCLUDED.account_created_on, number_of_appointments=EXCLUDED.number_of_appointments, number_of_virtual_appointments=EXCLUDED.number_of_virtual_appointments, number_of_documents_uploaded=EXCLUDED.number_of_documents_uploaded, number_of_members_added=EXCLUDED.number_of_members_added;

-- doctor_stats
INSERT INTO doctor_stats (id, account_created_on, number_of_appointments_diagnosed, number_of_virtual_appointments_diagnosed) VALUES (10, '2026-04-19', 10, 5) ON CONFLICT (id) DO UPDATE SET account_created_on=EXCLUDED.account_created_on, number_of_appointments_diagnosed=EXCLUDED.number_of_appointments_diagnosed, number_of_virtual_appointments_diagnosed=EXCLUDED.number_of_virtual_appointments_diagnosed;
INSERT INTO doctor_stats (id, account_created_on, number_of_appointments_diagnosed, number_of_virtual_appointments_diagnosed) VALUES (11, '2026-04-19', 8, 3) ON CONFLICT (id) DO UPDATE SET account_created_on=EXCLUDED.account_created_on, number_of_appointments_diagnosed=EXCLUDED.number_of_appointments_diagnosed, number_of_virtual_appointments_diagnosed=EXCLUDED.number_of_virtual_appointments_diagnosed;

-- members_data
INSERT INTO members_data (member_id, user_id, relation) VALUES (2, 1, 'Sister') ON CONFLICT (member_id) DO UPDATE SET user_id=EXCLUDED.user_id, relation=EXCLUDED.relation;

-- appointment_data
INSERT INTO appointment_data (id, mode, user_id, user_name, doctor_id, doctor_name, specialist, appointment_date, appointment_time, appointment_address, appointment_city, appointment_state) VALUES (1001, 'Virtual', 1, 'Khiem Pham', 10, 'An Nguyen', 'Family Physician', '2026-04-19', '10:00', 'Virtual', 'Virtual', 'Virtual') ON CONFLICT (id) DO UPDATE SET mode=EXCLUDED.mode, user_id=EXCLUDED.user_id, user_name=EXCLUDED.user_name, doctor_id=EXCLUDED.doctor_id, doctor_name=EXCLUDED.doctor_name, specialist=EXCLUDED.specialist, appointment_date=EXCLUDED.appointment_date, appointment_time=EXCLUDED.appointment_time, appointment_address=EXCLUDED.appointment_address, appointment_city=EXCLUDED.appointment_city, appointment_state=EXCLUDED.appointment_state;

-- documents
INSERT INTO documents (id, user_id, document_name, document, upload_date) VALUES (2001, 1, 'Ket qua xet nghiem mau', '\\x53616d706c6520646f63756d656e74206279746573'::bytea, '2026-04-19') ON CONFLICT (id) DO UPDATE SET user_id=EXCLUDED.user_id, document_name=EXCLUDED.document_name, document=EXCLUDED.document, upload_date=EXCLUDED.upload_date;

-- medication_reminders
INSERT INTO medication_reminders (id, admin_user_id, member_id, medicine_name, notes, morning_enabled, evening_enabled, start_date, end_date, is_active) VALUES (3001, 1, 1, 'Vitamin D', 'Sau an', TRUE, TRUE, '2026-04-19', NULL, TRUE) ON CONFLICT (id) DO UPDATE SET admin_user_id=EXCLUDED.admin_user_id, member_id=EXCLUDED.member_id, medicine_name=EXCLUDED.medicine_name, notes=EXCLUDED.notes, morning_enabled=EXCLUDED.morning_enabled, evening_enabled=EXCLUDED.evening_enabled, start_date=EXCLUDED.start_date, end_date=EXCLUDED.end_date, is_active=EXCLUDED.is_active;
